version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: docflow
      POSTGRES_PASSWORD: docflowpass
      POSTGRES_DB: docflow_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
